[project]
name = "json-file-storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "shaileshpandit141", email = "shaileshpandit141@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
]

[project.scripts]
json-file-storage = "json_file_storage:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
